apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-management.fullname" . }}-frontend
  labels:
    {{- include "event-management.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: frontend
